### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [Etto48/arcticglow-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by Etto48** [comment]
Thank you! I was going to add the MIT license but I didn't think that anyone would see this repo so fast! I'll add it now.
Thanks again.
